[platformio]
default_envs = mhetesp32minikit

[env]
framework = arduino
lib_ldf_mode = deep
monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson
    robtillaart/INA226
    https://github.com/ESP32Async/ESPAsyncWebServer.git
    https://github.com/ESP32Async/AsyncTCP.git

[espressif32_base]
platform = espressif32

build_unflags =
    -Werror=reorder

monitor_filters =
    esp32_exception_decoder

[env:mhetesp32minikit]
extends = espressif32_base

board = mhetesp32minikit

build_type = release

board_build.filesystem = spiffs

build_flags =
    -DCORE_DEBUG_LEVEL=0